### ISSUE TITLE
The grab scroll is not working properly

### ISSUE THREAD

**Issue by david1opez** [david1opez/Mentes-Brillantes#2]
on **index.html**
```html
    <body>
        <div>
          <div class="proyectsScreen">
               <div class="scroller"></div>
          </div>
        </div>
    <body>
```
on **index.html : 313**
```html
<script>
        document.addEventListener('DOMContentLoaded', function() {
            const ele = document.querySelector('.scroller');

            let pos = {left: 0, x: 0};

            const mouseDownHandler = function(e) {
                ele.style.userSelect = 'none';

                pos = {
                    left: ele.scrollLeft,
                    x: e.clientX,
                };

                document.addEventListener('mousemove', mouseMoveHandler);
                document.addEventListener('mouseup', mouseUpHandler);
            };

            const mouseMoveHandler = function(e) {
                const dx = e.clientX - pos.x;
                ele.scrollLeft = pos.left - dx;
            };

            const mouseUpHandler = function() {
                ele.style.removeProperty('user-select');
                document.removeEventListener('mousemove', mouseMoveHandler);
                document.removeEventListener('mouseup', mouseUpHandler);
            };
            
            ele.addEventListener('mousedown', mouseDownHandler);
        });
    </script>
```

on **proyects.css**
```css
 .proyectsScreen {
    position: relative;
    display: flex;
    flex-direction: column;
    align-items: center;
    justify-content: center;
}

.proyectsScreen h1 {
    position: relative;
    color: #000;
    opacity: 0.8;
    font-size: 9em;
}

.proyectsScreen .scroller {
    position: relative;
    display: grid;
    grid-template-columns: repeat(11, 250px);
    grid-gap: 90px;
    top: -14%;
    width: 100%;
    height: 400px;
    background-color: #FFC940;
    box-shadow: 0px -5px 19px rgb(0 0 0 / 25%);
    overflow: hidden;
}

.proyectsScreen .scroller .card {
    position: relative;
    text-align: center;
    height: 320px;
    top: 25px;
    background: #fff;
    box-shadow: 0px 4px 11px rgb(0 0 0 / 25%);
    margin-left: 20px;
}

.proyectsScreen .scroller .card h2 {
    padding-top: 15px;
    margin-bottom: 10px;
    font-size: 1.3em;
    font-weight: 600;
}

.proyectsScreen .scroller .card .image {
    position: relative;
    text-align: center;
    left: 7%;
    width: 86%;
    height: 210px;
    background:#fff;
    border: 3px solid #000;
}

.proyectsScreen .scroller .card .image img {
    width: 100%;
    height: 100%;
    object-fit: contain;
}

.proyectsScreen .scroller .card h1 {
    position: relative;
    top: 16%;
    width: 100%;
    opacity: 0.4;
    color: #ffffff;
    font-size: 2.3em;
}
```

on **index.html : 270 **
```javascript
        function createThings() {
            var appendTo = document.querySelector(".scroller");

            var card = document.createElement("div");
            var title = document.createElement("h2");
            var imageContainer = document.createElement("div");
            var image = document.createElement("img");
            var team = document.createElement("h1");
            
            card.classList.add("card");
            imageContainer.classList.add("image");
            
            title.innerHTML = "Foxset";
            team.innerHTML = "Equipo 2";

            image.src = "https://firebasestorage.googleapis.com/v0/b/mentesbrillantes-ec4b8.appspot.com/o/logos%2Ffoxset.png?alt=media&token=93878369-05b1-4d2a-baf2-ead2385c39ad"
            image.setAttribute("draggable", false);

            appendTo.appendChild(card);
            card.appendChild(title);
            card.appendChild(imageContainer);
            imageContainer.appendChild(image);
            card.appendChild(team)
        }
```
